### ISSUE TITLE
Provide for the ability to filter on categorization 

### ISSUE THREAD

**Issue by kevindoingbizas** [ComplianceAsCode/redhat#1107]
Provide for the ability to filter on categorization on Low, Moderate, High on the ATO pathways Product pages. http://atopathways.redhatgov.io/ato/products/openshift-container-platform-4/NIST-800-53

Appendix D https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r4.pdf

**Comment by shawndwells** [comment]
Hi @kevindoingbizas agreed on the idea! The ATO Pathways backend is developed over at https://github.com/RedHatGov/ocdb/. Would you mind creating a ticket over there?

This has been on our list, but without anyone specifically asking, was burried in the backlog. Really appreciate your opening an issue.

From a technical perspective the various certifications like FISMA/FedRAMP/ICD are enumerated in the OpenControl community:
https://github.com/opencontrol/certifications/

Should be possible to show all control responses based on a profile/certification enumerated there. 


+cc @isimluk for awareness (since he'd be the one actually writing the code!)

**Comment by redhatrises** [comment]
@isimluk haven't we already done this?

**Comment by isimluk** [comment]
Indeed!

**Comment by isimluk** [comment]
Interestingly, I don't have the privileges to close this.

**Comment by redhatrises** [comment]
Odd... I'll close it.
